### ISSUE TITLE
Can this work for css?

### ISSUE THREAD

**Issue by mp3096** [LehaSex/CS2BhopPython#1]
can u release for counter strike source i changed around but doesnt seem to work in css game. can you release one for css would be great thank you.

**Comment by LehaSex** [comment]
Hello! I did this for CSS. Check out the releases.
See https://github.com/LehaSex/CS2BhopPython/releases
Download the `temp` folder from the CSS branch
https://github.com/LehaSex/CS2BhopPython/tree/CSSBhopPython
